repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      # linting with automated fixing
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      # formatting, drop-in replacement for black
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        exclude: |
          Pipfile|
          Pipfile.lock|
          (\/.*?\.[\w:]+)/Pipfile.lock|
          (\/.*?\.[\w:]+)/pyproject.toml|
          poetry.lock|
          (\/.*?\.[\w:]+)/poetry.lock
        args:
          [
            "--ignore-words-list",
            "implementors",
          ]
